spring:
  kafka:
    log:
      topic: logs

logstash:
  host: localhost

kafka:
  bootstrap-servers: localhost:9094

logging:
  pattern:
    level: %5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sapling:
      probability: 1.0

redis:
  service:
    prefix: CMN-SW:RDS
    ttl: 3000
    cacheable:
      ttl: 180
  server:
    address: localhost
    port: 6379
    cluster:
      nodes:
    password:
    environment: live
